services:
  mysql-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: 280720/mysql-server-node:1.0
    container_name: mysql-server-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - ./server/init_server.sql:/init_db/init_server.sql
      - ./server/init_db.sh:/init_db/init_db.sh
    networks:
      mysql_network:
        ipv4_address: 192.168.122.11
    command: ["sh","-c","chmod +x /init_db/init_server.sql && chmod +x /init_db/init_db.sh && mysqld && sh ./init_db/init_db.sh"]


  mysql-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: 280720/mysql-client-node:1.0
    container_name: mysql-client-container
    networks:
      mysql_network:
        ipv4_address: 192.168.122.10
    depends_on:
      - mysql-server

networks:
  mysql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.122.0/24
